query getRestaurant($id: ID!) {
  restaurant(id: $id) {
    id
    name
    phone
    icon
    schedule {
      days
      openAt
      closeAt
    }
    menu {
      name
      price
      includeBread
      includeBeverage
      sections {
        title
        items
      }
    }
  }
}

query getMyRestaurant {
  myRestaurant {
    id
    name
    phone
    icon
    schedule {
      days
      openAt
      closeAt
    }
    menu {
      name
      price
      includeBread
      includeBeverage
      sections {
        title
        items
      }
    }
  }
}

mutation saveRestaurant($restaurant: RestaurantInput!) {
  saveRestaurant(restaurant: $restaurant) {
    updated
  }
}
