type Section {
  title: String!
  items: [String!]!
}
input SectionInput {
  title: String!
  items: [String!]!
}

type Menu {
  price: Float
  name: String!
  includeBread: Boolean
  includeBeverage: Boolean
  sections: [Section!]
}
input MenuInput {
  price: Float
  name: String!
  includeBread: Boolean
  includeBeverage: Boolean
  sections: [SectionInput!]
}

type Schedule {
  days: [Boolean!]
  openAt: Int!
  closeAt: Int!
}
input ScheduleInput {
  days: [Boolean!]
  openAt: Int!
  closeAt: Int!
}

type Restaurant {
  id: ID!
  name: String!
  phone: String
  icon: String
  menu: Menu!
  schedule: Schedule!
}
input RestaurantInput {
  name: String!
  phone: String
  icon: String
  menu: MenuInput!
  schedule: ScheduleInput!
}

type Query {
  restaurant(id: ID!): Restaurant
  myRestaurant: Restaurant
}

type Mutation {
  saveRestaurant(restaurant: RestaurantInput!): SaveOutput!
}
